# vue-app netlify.toml
[build]
    base = "/vue-app"
    command = "vite build"
    functions = "/netlify/functions"
    publish = "/dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  ## Sets a custom directory for Netlify Functions
  directory = "netlify/functions/"

  ## Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

  ## Flags "node-fetch" as an external node module for all functions
  external_node_modules = ["node-fetch"]