# vue-app netlify.toml
[build]
    base = "/vue-app"
    command = "vite build"
    functions = "/vue-app/.netlify/functions"
    publish = "/vue-app/dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200